### ISSUE TITLE
FISHEYE_INST should not be a literal path

### ISSUE THREAD

**Issue by AnthonyMastrean** [johnlawerance/crucible#9]
When the [installation guide](https://confluence.atlassian.com/fisheye/installing-fisheye-on-linux-and-mac-298976962.html) talks about "[FISHEYE_INST](https://confluence.atlassian.com/fisheye/environment-variables-298976934.html)", it's referring to an environment variable, not [a literal path](https://github.com/johnlawerance/crucible/blob/master/manifests/init.pp#L10).

It's fine for the module to provide a sane default. Atlassian doesn't really provide any guidance. Either of these is reasonable.

 * `/opt/crucible-data`
 * `/home/crucible/crucible` (as long as the module is managing the user)

You might set the environment variable, too. I'm not sure if it's used by any tooling other than the [init script](https://github.com/johnlawerance/crucible/blob/master/templates/crucible-init.sh.erb#L15).

**templates/crucible-env.sh.erb => /etc/profile.d/crucible.sh**
```
export FISHEYE_INST=<% scope.lookupvar('::crucible::fisheye_inst') %>
```

**Comment by johnlawerance** [comment]
Thanks @AnthonyMastrean I think it makes sense to change the data directory to something more obvious. /opt/crucible-data sounds like a good plan.

As far as I can tell the only place FISHEYE_INST is really used is in the init script (which I have set there instead of exporting as an environment variable). I'd be fine with either.
